project:
  type: website

website:
  title: "Grace's LLM Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/grace-kneidel

format:
  html:
    theme: flatly
    css: styles.css

execute:
  freeze: auto
